project_name: "TEP-Anomaly-Detection"
entity: "avdalovica"
experiment_name: "tep_ccann_test"
dataset_name: "TEP"

# Level names for TEP
level_names: ["Sensors", "Relationships", "Subprocesses"]

# System configuration
system:
  device: "cuda" # "cuda" or "cpu"
  checkpoint_dir: "model_checkpoints"

# Data configuration
data:
  dataset: "TEP" # Options: SWAT, WADI, TEP
  data_dir: "data/TEP"
  train_path: "TEP_train.csv"
  test_path: "TEP_test_cons_p2s_s1.csv"
  sample_rate: 0.2
  validation_split_ratio: 0.2
  temporal_mode: false # False for reconstruction, True for temporal prediction
  temporal_sample_rate: 1 # Subsample data for temporal mode. 1 = no sampling.

# Model configuration
model:
  name: "AnomalyCCANN"
  use_tcn: false # Whether to use TCN for temporal modeling
  n_input: 10 # For temporal mode
  channels_per_layer:
    - - [3, 6, 4] # in_channels (0-cells: 3D, 1-cells: 6D, 2-cells: 4D)
      - [32, 32, 32] # intermediate_channels
      - [64, 64, 64] # final_channels

# Training configuration
training:
  epochs: 5
  batch_size: 32 # HMC usually works with batch_size=1
  learning_rate: 0.001
  weight_decay: 1e-5
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: true
    patience: 2
    min_delta: 1e-4

# Anomaly detection configuration
anomaly_detection:
  threshold_method: "percentile" # or "mean_sd"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: false
  temporal_consistency: 6

# Evaluation configuration
evaluation:
  method: threshold  # 'threshold' or 'cusum'
  threshold_percentile: 99.0
  fp_alarm_window_seconds: 60
  cusum_S: 1.42
  cusum_G: 5.98

# Enhanced time-aware metrics
enhanced_time_aware_metrics:
  theta_p: 0.5
  theta_r: 0.1
  original_sample_hz: 1 