# Configuration for WADI Anomaly Detection Experiments

# -- Experiment Settings --
experiment_name: "wadi_improved_ccann"
project_name: "TopoDetect"
entity: "avdalovica"

# -- Dataset Configuration --
dataset_name: "WADI"  # Dataset name for attack indices
level_names: ["Nodes", "Edges", "PLCs"]  # Custom names for topological levels

# -- Data Settings --
data:
  dataset: "WADI" # Options: SWAT, WADI, TEP
  data_dir: "data/WADI"
  train_path: "WADI_train.csv"
  test_path: "WADI_test.csv"
  sample_rate: 0.2
  validation_split_ratio: 0.2
  temporal_mode: False # False for reconstruction, True for temporal prediction
  temporal_sample_rate: 1 # Subsample data for temporal mode. 1 = no sampling.

# -- Model Hyperparameters --
model:
  name: "AnomalyCCANN"
  channels_per_layer:
    - - [3, 6, 4] # in_channels (0-cells: 3D, 1-cells: 6D, 2-cells: 4D)
      - [32, 32, 32] # intermediate_channels
      - [64, 64, 64] # final_channels
  n_input: 10  # For temporal mode

# -- Training Parameters --
training:
  epochs:  5
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 1e-5
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: True
    patience: 10
    min_delta: 1e-4

# -- Anomaly Detection Parameters --
anomaly_detection:
  threshold_method: "percentile" # or "mean_sd"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: False
  temporal_consistency: 6

# -- Evaluation Parameters --
evaluation:
  method: "threshold"  # Options: "threshold", "cusum"
  fp_alarm_window_seconds: 60
  cusum_S: 1.42
  cusum_G: 5.98

# -- Enhanced Time-Aware Metrics --
enhanced_time_aware_metrics:
  theta_p: 0.5  # Detection threshold for precision
  theta_r: 0.1  # Detection threshold for recall
  original_sample_hz: 1  # Original sampling frequency (1 Hz for WADI)

# -- System Configuration --
system:
  device: "cuda"  # Options: "cuda", "cpu"
  checkpoint_dir: "checkpoints" 