# Configuration for Anomaly Detection Experiments

# -- Experiment Settings --
experiment_name: "swat_improved_ccann"
project_name: "TopoDetect"
entity: "avdalovica"

# -- Dataset Configuration --
dataset_name: "SWAT"  # Dataset name for attack indices (e.g., "SWAT", "WADI", "TEP")
level_names: ["Nodes", "Edges", "PLCs"]  # Custom names for topological levels

# Example for WADI dataset:
# dataset_name: "WADI"
# level_names: ["Sensors", "Actuators", "Controllers"]

# Example for TEP dataset:
# dataset_name: "TEP"  
# level_names: ["Variables", "Connections", "Units"]

# -- Data Settings --
data:
  dataset: "SWAT" # Options: SWAT, WADI, TEP
  data_dir: "data/SWAT"
  train_path: "SWATv0_train.csv"
  test_path: "SWATv0_test.csv"
  sample_rate: 0.005
  validation_split_ratio: 0.2
  temporal_mode: False # False for reconstruction, True for temporal prediction
  temporal_sample_rate: 1 # Subsample data for temporal mode. 1 = no sampling.

# -- Model Hyperparameters --
model:
  name: "AnomalyCCANN"
  use_tcn: False # Whether to use TCN for temporal modeling
  n_input: 10 # For temporal mode
  channels_per_layer:
    - - [3, 6, 3] # in_channels (0-cells: 3D, 1-cells: 6D, 2-cells: 3D) 
      - [32, 32, 32] # intermediate_channels
      - [64, 64, 64] # final_channels

# -- Training Settings --
training:
  epochs: 2
  batch_size: 1 # HMC usually works with batch_size=1
  learning_rate: 0.001
  weight_decay: 1e-5
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: True
    patience: 2
    min_delta: 1e-4

# -- Anomaly Detection Settings --
anomaly_detection:
  threshold_method: "percentile" # or "mean_sd"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: False
  temporal_consistency: 6

# -- Evaluation Settings --
evaluation:
  method: "threshold"  # 'threshold' or 'cusum'
  threshold_percentile: 99.0
  fp_alarm_window_seconds: 60
  cusum_S: 1.42
  cusum_G: 5.98

# -- Enhanced Time-Aware Metrics Settings --
enhanced_time_aware_metrics:
  theta_p: 0.5          # Detection threshold for precision (default: 0.5)
  theta_r: 0.1          # Detection threshold for recall (default: 0.1)
  original_sample_hz: 1  # Original sampling frequency in Hz (SWAT: 1 Hz, WADI: 1 Hz)

# -- System Settings --
system:
  device: "cuda" # "cuda" or "cpu"
  checkpoint_dir: "model_checkpoints" 