# GECO SWAT Flow Difference Experiment Configuration
# Testing flow balance features for PLC zones with physics-based process dynamics

# Reproducibility
seed: 42

project_name: "esorics_geco_flow_test"
entity: "avdalovica"
experiment_name: "geco_swat_flow_physics_experiment"
dataset_name: "SWAT"

# System configuration
system:
  device: "cuda"
  checkpoint_dir: "checkpoints"

# Data configuration
data:
  data_dir: "data/SWAT"
  train_path: "SWATv0_train.csv"
  test_path: "SWATv0_test.csv"
  sample_rate: 0.1  # Increased to 10% for better evaluation
  validation_split_ratio: 0.2
  temporal_mode: false
  temporal_sample_rate: 1
  normalization_method: "mixed_normalization"  # Use mixed normalization (z-score for sensors, min-max for actuators)
  use_enhanced_2cell_features: true  # Use enhanced 2-cell features
  use_first_order_differences: true  # Enable first-order differences for 0-cells ONLY
  use_first_order_differences_edges: false  # NEW: Disable first-order differences for 1-cells (edges)
  use_flow_balance_features: true  # NEW: Enable flow balance features for PLCs (FIT{X}01 - FIT{X+1}01)

# Topology configuration
topology:
  use_geco_relationships: true    # Use GECO-learned relationships
  use_geco_features: true         # Use enhanced edge features with GECO info

# Model configuration
model:
  name: "AnomalyCCANN"
  channels_per_layer:
    - [[2, 3, 5], [32, 32, 32], [64, 64, 64]]  # Updated dimensions: 2D 0-cells, 3D 1-cells, 5D 2-cells
  original_feature_dims:
    "0": 2  # 0-cells: 2D features (normalized value + first-order difference)
    "1": 3  # 1-cells: 3D features (two concatenated real values + GECO strength, NO differences)
    "2": 5  # 2-cells: 5D features (original 4D + flow balance feature)
  temporal_mode: false
  use_tcn: false
  n_input: 10

# Training configuration
training:
  epochs: 5  # More epochs for better evaluation
  batch_size: 1  # Larger batch size with more data
  learning_rate: 0.001
  weight_decay: 0.00001
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

# Anomaly detection configuration
anomaly_detection:
  temporal_consistency: 3
  threshold_method: "percentile"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: false

# Evaluation configuration
evaluation:
  method: "threshold"
  fp_alarm_window_seconds: 60

# Enhanced time-aware metrics
enhanced_time_aware_metrics:
  theta_p: 0.5
  theta_r: 0.01
  original_sample_hz: 1 