# GECO WADI Test Configuration
# Testing GECO-learned relationships on 0.1 sample rate

# Reproducibility
seed: 42

project_name: "esorics_geco_test"
entity: "avdalovica"
experiment_name: "geco_wadi_test_01"
dataset_name: "WADI"

# System configuration
system:
  device: "cuda"
  checkpoint_dir: "checkpoints"

# Data configuration
data:
  data_dir: "data/WADI"
  train_path: "WADI_train.csv"
  test_path: "WADI_test.csv"
  sample_rate: 0.1 # Small sample for testing
  validation_split_ratio: 0.2
  temporal_mode: false
  temporal_sample_rate: 1
  normalization_method: "mixed_normalization"  # Use mixed normalization (z-score for sensors, min-max for actuators)
  use_enhanced_2cell_features: true  # Use enhanced 2-cell features with min/max stats

# Topology configuration - NEW SECTION
topology:
  use_geco_relationships: true    # Use GECO-learned relationships
  use_geco_features: true         # Use enhanced edge features with GECO info

# Model configuration
model:
  name: "AnomalyCCANN"
  channels_per_layer:
    - [[1, 3, 4], [32, 32, 32], [64, 64, 64]]  # Updated for simplified features (1D, 3D, 4D)
  original_feature_dims:
    "0": 1  # 0-cells: 1D features (mixed normalization)
    "1": 3  # 1-cells: 3D features (2D concatenated + 1D GECO normalized strength)
    "2": 4  # 2-cells: 4D features (mean/std sensors, median/range actuators)
  temporal_mode: false
  use_tcn: false
  n_input: 10

# Training configuration
training:
  epochs: 5
  batch_size: 1
  learning_rate: 0.001
  weight_decay: 0.0001
  grad_clip_value: 1.0
  test_interval: 1  # Changed from 5 to 1 to evaluate after each epoch
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

# Anomaly detection configuration
anomaly_detection:
  temporal_consistency: 3
  threshold_method: "percentile"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: false

# Evaluation configuration
evaluation:
  method: "threshold"  # Changed from "time_aware" to "threshold"
  fp_alarm_window_seconds: 60

# Enhanced time-aware metrics
enhanced_time_aware_metrics:
  theta_p: 0.5
  theta_r: 0.01
  original_sample_hz: 1 