# Configuration for Anomaly Detection Experiments - Enhanced 2-Cell Features (Dual Threshold)

# -- Experiment Settings --
experiment_name: "swat_enhanced_2cell_dual_threshold_stabilized_ccann"
project_name: "TopoDetect"
entity: "avdalovica"

# -- Dataset Configuration --
dataset_name: "SWAT"  # Dataset name for attack indices (e.g., "SWAT", "WADI", "TEP")
level_names: ["Nodes", "Edges", "PLCs"]  # Custom names for topological levels

# -- Data Settings --
data:
  dataset: "SWAT" # Options: SWAT, WADI, TEP
  data_dir: "data/SWAT"
  train_path: "SWATv0_train.csv"
  test_path: "SWATv0_test.csv"
  sample_rate: 0.01
  validation_split_ratio: 0.2
  temporal_mode: False # False for reconstruction, True for temporal prediction
  temporal_sample_rate: 1 # Subsample data for temporal mode. 1 = no sampling.
  # Feature engineering parameters
  normalization_method: "mixed_normalization" # Z-norm for sensors, min-max for actuators
  use_enhanced_2cell_features: True # Use 4D enhanced 2-cell features
  # Note: First 21600 points (6 hours) are automatically removed from training data for SWAT stabilization

# -- Model Hyperparameters --
model:
  name: "AnomalyCCANN"
  use_tcn: False # Whether to use TCN for temporal modeling
  n_input: 10 # For temporal mode
  channels_per_layer:
    - - [1, 2, 8] # in_channels (0-cells: 1D, 1-cells: 2D, 2-cells: 8D) 
      - [32, 32, 32] # intermediate_channels
      - [64, 64, 64] # final_channels

# -- Training Settings --
training:
  epochs: 2
  batch_size: 1 # HMC usually works with batch_size=1
  learning_rate: 0.0005
  weight_decay: 1e-5
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: True
    patience: 2
    min_delta: 1e-4

# -- Anomaly Detection Settings --
anomaly_detection:
  threshold_method: "percentile" # or "mean_sd"
  threshold_percentile: 99.0
  sd_multiplier: 2.5
  use_component_thresholds: False
  temporal_consistency: 2
  use_two_threshold_alarm: True # Enable two-threshold strategy for PLCs
  plc_low_percentile: 99.0      # Lower, sensitive threshold for PLCs
  plc_high_percentile: 99.9     # Higher, high-confidence threshold for PLCs

# -- Evaluation Settings --
evaluation:
  method: "threshold"  # 'threshold' or 'cusum'
  threshold_percentile: 99.0
  fp_alarm_window_seconds: 60
  cusum_S: 1.42
  cusum_G: 5.98

# -- Enhanced Time-Aware Metrics Settings --
enhanced_time_aware_metrics:
  theta_p: 0.5          # Detection threshold for precision (default: 0.5)
  theta_r: 0.1          # Detection threshold for recall (default: 0.1)
  original_sample_hz: 1  # Original sampling frequency in Hz (SWAT: 1 Hz, WADI: 1 Hz)

# -- System Settings --
system:
  device: "cuda" # "cuda" or "cpu"
  checkpoint_dir: "model_checkpoints" 