# WADI Attack Detection Features Experiment - GECO VERSION
# Testing attack-specific 2-cell features with GECO-learned relationships and enhanced edge features
# Using 10% of data for better evaluation

seed: 42

project_name: "WADI_TopoDetect"
entity: "avdalovica"
experiment_name: "wadi_attack_detection_features_geco_10p"
dataset_name: "WADI"

# System configuration
system:
  device: "cuda"
  checkpoint_dir: "checkpoints"

# Data configuration - 10% SAMPLE FOR BETTER EVALUATION
data:
  data_dir: "data/WADI"
  train_path: "WADI_train.csv"
  test_path: "WADI_test.csv"
  sample_rate: 0.1  # 10% for better evaluation
  validation_split_ratio: 0.2
  temporal_mode: false
  temporal_sample_rate: 1
  normalization_method: "mixed_normalization"  # Z-norm for sensors, min-max for actuators
  use_enhanced_2cell_features: true  # Enable attack-specific features
  use_first_order_differences: false  # Disable for simplicity
  use_first_order_differences_edges: false
  use_attack_detection_features: true  # Enable attack-specific features

# Topology configuration - GECO RELATIONSHIPS AND FEATURES
topology:
  use_geco_relationships: true   # Use GECO-learned relationships
  use_geco_features: true        # Enable enhanced edge features with GECO info
  use_pure_embedding: false      # NO pure embedding

# Model configuration - ATTACK DETECTION FEATURES + GECO
model:
  name: "AnomalyCCANN"
  channels_per_layer:
    - [[1, 3, 6], [32, 32, 32], [64, 64, 64]]  # 6D GECO edge features, 6D attack detection features
  original_feature_dims:
    "0": 1   # 0-cells: 1D normalized values
    "1": 3  # 1-cells: 2D concatenated values + 4D GECO features
    "2": 6   # 2-cells: 6D attack detection features
  use_enhanced_decoders: false  # Disable for testing

# Training configuration
training:
  epochs: 5  # More epochs for better evaluation
  batch_size: 64  # Standard batch size
  learning_rate: 0.001  # Standard learning rate
  weight_decay: 1e-4
  grad_clip_value: 1.0
  test_interval: 1
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 1e-4

# Anomaly detection
anomaly_detection:
  threshold_method: "percentile"  # Use percentile like working config
  threshold_percentile: 99.0
  evaluation_method: "threshold"
  use_two_threshold_alarm: false
  temporal_consistency: 3

# Evaluation
evaluation:
  metrics: ["f1", "precision", "recall", "auc"]
  save_predictions: true
  save_reconstruction_errors: true

# Logging
logging:
  use_wandb: true
  log_interval: 5
  save_model: true
  verbose: true 